@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.infamous.dungeons_libraries.test.mod;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;